# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-11-02 09:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('axfxx1806', '0002_mustbuy_nav'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='mustbuy',
            table='axf_mustbuy',
        ),
    ]
