# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-11-05 13:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('axfxx1806', '0008_auto_20181105_1043'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField(default=1)),
                ('crteate_time', models.DateTimeField()),
                ('upload_time', models.DateTimeField(auto_now_add=True)),
                ('is_delete', models.BooleanField(default=True)),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='axfxx1806.Goods')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='axfxx1806.MyUser')),
            ],
            options={
                'verbose_name': '购物车',
            },
        ),
        migrations.AlterIndexTogether(
            name='cart',
            index_together=set([('user', 'goods')]),
        ),
    ]
