# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-11-06 03:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('axfxx1806', '0012_remove_minebtns_is_used'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='icon',
            field=models.ImageField(null=True, upload_to='icon'),
        ),
    ]
