# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-11-06 04:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('axfxx1806', '0014_auto_20181106_1247'),
    ]

    operations = [
        migrations.CreateModel(
            name='MineBtns',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('btn', models.CharField(max_length=30)),
                ('class_name', models.CharField(max_length=100)),
                ('bref_url', models.CharField(max_length=255, null=True)),
                ('is_used', models.BooleanField(default=True, verbose_name='是否正在使用')),
            ],
            options={
                'verbose_name': '我的页面的下一排按钮',
            },
        ),
        migrations.AlterModelOptions(
            name='cart',
            options={'verbose_name': '购物车'},
        ),
        migrations.AlterIndexTogether(
            name='cart',
            index_together=set([('user', 'goods')]),
        ),
    ]
